server:
  port: 0
spring:
  application:
    name: transactional-service
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      #      retries: 10
      properties:
        #        retry.backoff.ms: 1000
        delivery.timeout.ms: 20000
        linger.ms: 0
        request.timeout.ms: 10000
        enable.idempotence: true