server:
  port: 0
spring:
  application:
    name: account-microservice
  kafka:
    bootstrap-servers: localhost:19092,localhost:19093,localhost:19094
    consumer:
      group-id: account-group
      properties:
        spring.json.trusted.packages: com.example.core.dto.event
  datasource:
    url: jdbc:h2:mem:h2
    username: h2
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org.springframework.kafka: INFO
    org.springframework.transaction: INFO
    org.springframework.orm.jpa.JpaTransactionManager: INFO

    org.apache.kafka.clients.producer: INFO
    org.apache.kafka.clients.producer.internals.TransactionManager: INFO
    org.apache.kafka.clients.consumer: INFO